(#9) Adds Jenkins-Set-Prefix Hook Package
chocolatey-community/chocolatey-hooks pull request #10
Opened 2023-03-23 12:21 UTC by JPRuskin

Due to the way Jenkins' MSI installs, changes to the Jenkins.xml configuration file can be unset (though backed up).

This hook sets the Prefix value after every installation of Jenkins, ensuring that paths won't break unexpectedly.

There is a parameter (`/prefix`) that can be passed to set the path you want, though it defaults to `jenkins` (e.g. accessing Jenkins via `yoursitehere.local/jenkins`).

I considered having a blank default, and removing the prefix if you didn't provide one, but decided that anyone who ran `choco install jenkins-set-prefix.hook` probably _did_ want a prefix of some kind.

Additional consideration: Should this run the same logic on install, such that people can use it to set a prefix on an already installed Jenkins instance without running `choco install jenkins --force` (or waiting for an upgrade)? If so, I'd split bits into a function file.

2023-03-23 12:43 UTC, JPRuskin commented on src/jenkins-set-prefix.hook/jenkins-set-prefix.hook.nuspec
> +`choco install jenkins-set-prefix.hook --parameters="/Prefix=ci"`</description>
I could mention, but don't think I should, that you can also adjust this by editing the file in the hooks folder... but that's not something we would want to encourage, I suspect.

2023-03-23 13:53 UTC, steviecoaster requested changes

2023-03-23 13:53 UTC, steviecoaster commented on src/jenkins-set-prefix.hook/tools/chocolateyInstall.ps1
> +if (-not $PSScriptRoot) {
We should _probably_ use `$toolsDir` here instead of `$PSScriptRoot` just to be consistent with historical packaging techniques and long-standing packages.

2023-03-23 13:53 UTC, steviecoaster commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +if (-not $PSScriptRoot) {
We likely should formulate some sort of "standard" here. I propose we use `$hookDir` to go with the longstanding use of `$toolsDir` in packaging. Though I'm fully aware it is _the same darn thing_.

2023-03-23 13:55 UTC, steviecoaster commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +if (-not $PSScriptRoot) {
There's a bit more to unpack here in thinking about it a little more. You'll need to make this a dependency on the `jenkins` package to ensure it gets picked up, and subsequently fired off.

And since there will be a change to the `jenkins` package to make that work, it seems that we could drop the use of a text file here and just pick up `$env:ChocolateyPackageParameters` in the hook script itself, and do the right things from there. 🤔

2023-03-23 13:56 UTC, steviecoaster commented
There's a bit more to unpack here in thinking about it a little more. You'll need to make this a dependency on the jenkins package to ensure it gets picked up, and subsequently fired off.

And since there will be a change to the jenkins package to make that work, it seems that we could drop the use of a text file here and just pick up $env:ChocolateyPackageParameters in the hook script itself, and do the right things from there. 🤔

2023-03-23 14:00 UTC, AdmiringWorm commented
> There's a bit more to unpack here in thinking about it a little more. You'll need to make this a dependency on the jenkins package to ensure it gets picked up, and subsequently fired off.

Don't do this at the moment, while it is fine for internal packages to have a dependency on hook package, we have had talks before that it may not be something we will allow on the community repository as it could potentially open up the user to have something being done on their computer that they have no idea of.

2023-03-23 18:31 UTC, TheCakeIsNaOH commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +if (-not $PSScriptRoot) {
`$hookDir` sounds good to me.

2023-03-23 18:34 UTC, TheCakeIsNaOH commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +$Prefix = Get-Content -Path $PSScriptRoot\prefixvalue.txt
Instead of storing the value in the hook folder, this probably should be moved to the config, and accessed with `Get-ChocolateyConfigValue`.
https://github.com/chocolatey/choco/issues/2854

2023-03-23 20:20 UTC, JPRuskin commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +$Prefix = Get-Content -Path $PSScriptRoot\prefixvalue.txt
I'd agree, but I don't think that'll be included in Chocolatey until 2.0/2.1. 

Would it be acceptable to add a function file (as I'm currently starting to do) and then write something similar to:
```
if (-not (Get-Command Get-ChocolateyConfigValue)) {
    <#Define a function that replicates this sort of thing #> 
}
```

That way, we can provide support for v1 and v2. Alternatively, I'll ask Gary if he thinks we'll be able to backport that functionality - but that may be unlikely, to be honest.

2023-03-23 20:34 UTC, pauby commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +$Prefix = Get-Content -Path $PSScriptRoot\prefixvalue.txt
> we'll be able to backport that functionality - but that may be unlikely, to be honest.

That's not something we will be doing.

2023-03-23 20:44 UTC, JPRuskin commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +if (-not $PSScriptRoot) {
I've made this change locally, but won't push it until I've finished up my refactor into a functions psm1.

2023-03-23 21:28 UTC, TheCakeIsNaOH commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +$Prefix = Get-Content -Path $PSScriptRoot\prefixvalue.txt
> Would it be acceptable to add a function file (as I'm currently starting to do) and then write something similar to:

That would work on a technical level, as far as I'm aware. I personally prefer not to do this, and instead focus on getting helpers in Chocolatey CLI or in an `.extension`.

But I'm only one of the maintainers of this repository, so I'm happy for other viewpoints.

> I'll also say that, though I prefer the idea of a single solution for all packages, I feel slightly odd storing this value in a Chocolatey config

It is a bit weird, from what it is currently used for, but according to Gary, it was always intended to hold more information. 

One advantage is that the chocolatey config file already has ChocolateyGUI integration.

2023-07-14 10:35 UTC, JPRuskin commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +$Prefix = Get-Content -Path $PSScriptRoot\prefixvalue.txt
So, I waited to try and integrate this with the PR (now it's been released as part of 2.1), but after trying it and discussing it with Gary I realise that it's still unready for package-level variables (even if I didn't want to support 1.*). 
We need to discuss and work on it internally, so for now I'll not use it here - but I'm getting requests for this hook package to be more publicly available.

Based on your preference, I'm happy to either:
- Continue PRing the hook package to this repository, and update it when we have agreement on exactly what's going on with package-config-in-config _or_
- Move it to my own repository, and look at moving it back when we can make it a great example package

Which do you prefer?

2023-07-17 12:46 UTC, pauby commented on src/jenkins-set-prefix.hook/hook/post-install-jenkins.ps1
> +$Prefix = Get-Content -Path $PSScriptRoot\prefixvalue.txt
Remember that for customers, we continue to support 1.x. Whether the use case for this is not customers using 1.x or not is a different question.

Is this solution not for customers using QSH / C4BAE? If that is the case, I'm unsure here is the best place for it.

2024-06-12 12:54 UTC, closed without merging