Remove desktop shortcuts
chocolatey-community/chocolatey-hooks pull request #3
Opened 2022-09-18 22:47 UTC by TheCakeIsNaOH

TODO, fill in.
Draft, not fully tested yet.

Fixes #2

2022-10-27 03:33 UTC, TheCakeIsNaOH commented
Well, this is ready for review now.

2022-10-27 19:14 UTC, corbob reviewed
Just the one comment regarding the versioning of this. Other than that, the code still looks good. I'll take it for a test run in a VM before putting a stamp of approval on it.

Note: I don't seem to have permissions to merge on this repository, so the best I can do is provide a stamp of approval :)

2022-10-27 19:14 UTC, corbob commented on src/cleanup-desktop-shortcuts.hook/cleanup-desktop-shortcuts.hook.nuspec
> +    <version>0.0.1-pre</version>
Is it intentional that this is a prerelease version?

2022-10-28 01:07 UTC, TheCakeIsNaOH commented on src/cleanup-desktop-shortcuts.hook/cleanup-desktop-shortcuts.hook.nuspec
> +    <version>0.0.1-pre</version>
At the moment it is a placeholder value since versioning is not something that we have set up guidelines for in regard to hook packages. And I had it prerelease since this package not something that has been widely tested (yet) and can delete data. 

But I'm open to suggestions.

2022-10-28 18:07 UTC, corbob requested changes

2022-10-28 18:07 UTC, corbob commented on src/cleanup-desktop-shortcuts.hook/hook/post-install-all.ps1
> +    Write-Host "Removing '$($postshortcut.name)'"
```suggestion
        if ($cleanup_desktop_shortcuts_hook_pre_shortcuts.fullname.Contains($postshortcut.fullname)) {
            Write-Debug "'$($postshortcut.fullname)' existed before install script run, ignoring"
            continue;
        }
    }
    Write-Host "Removing '$($postshortcut.fullname)'"
```

I encountered a test scenario where the previous check wouldn't be sufficient: If the running user put back the desktop shortcut, then it would be `Firefox.lnk` in the current user desktop, but would be checking that `Firefox.lnk` from the common desktop.

2022-10-28 18:08 UTC, corbob commented on src/cleanup-desktop-shortcuts.hook/cleanup-desktop-shortcuts.hook.nuspec
> +    <version>0.0.1-pre</version>
That seems like a reasonable reason to mark it as prerelease. I have no concerns one way or another regarding the version. Will leave this comment unresolved to remind us to make the conscious decision on the version before merging.

2022-10-28 18:29 UTC, pauby commented on src/cleanup-desktop-shortcuts.hook/hook/post-install-all.ps1
> +[array]$global:cleanup_desktop_shortcuts_hook_post_shortcuts = Get-Childitem -Path ([environment]::GetFolderPath("DesktopDirectory")) -Filter "*.lnk"
I'm looking at this on my phone so the context might be obvious on a full screen desktop, but are we using PowerShell variables with underscores?

2022-10-28 19:23 UTC, vexx32 reviewed
A few comments/recommendations but otherwise this looks good. Nice work! 💖

2022-10-28 19:23 UTC, vexx32 commented on src/cleanup-desktop-shortcuts.hook/hook/post-install-all.ps1
> +[array]$global:cleanup_desktop_shortcuts_hook_post_shortcuts = Get-Childitem -Path ([environment]::GetFolderPath("DesktopDirectory")) -Filter "*.lnk"
Yeah. That aside, this variable name is excessively long as well IMO. Would it be more appropriate to store this in an environment variable so the latter script can retrieve it?

For the name... probably part of the intent is to avoid other users' package scripts accidentally conflicting with it, but I don't think underscores are necessary for that.

If we're not going to use an env var, to minimise potential collisions I'd say we should use a single hashtable instead of two distinct variables.

```suggestion
$global:CleanupShortcutsHook.PostShortcuts = @(Get-Childitem -Path ([environment]::GetFolderPath("DesktopDirectory")) -Filter "*.lnk")
```

If variable collision is something we really want to worry about, I would recommend we use `New-Module` to create an ephemeral module scope to store the data in, so that users' package scripts can't conflict with it. We can pull the variable out of the module using `$localVar = & (Get-Module TemporaryModuleName) { $moduleVariableName }`. Storing it in a module scope also means we don't need to pollute the global scope or environment variables as well.

2022-10-28 19:23 UTC, vexx32 commented on src/cleanup-desktop-shortcuts.hook/hook/post-install-all.ps1
> +    Write-Host "Removing '$($postshortcut.name)'"
If we're comparing `FullName` we're probably just best off using `-eq`

2022-10-28 19:23 UTC, vexx32 commented on src/cleanup-desktop-shortcuts.hook/hook/pre-install-all.ps1
> +[array]$global:cleanup_desktop_shortcuts_hook_pre_shortcuts = Get-Childitem -Path ([environment]::GetFolderPath("DesktopDirectory")) -Filter "*.lnk"
Matching suggestion for the other script.

```suggestion
$global:CleanupShortcutsHook = @{
    PreShortcuts = @(Get-Childitem -Path ([environment]::GetFolderPath("DesktopDirectory")) -Filter "*.lnk")
}
```

2022-11-01 21:12 UTC, TheCakeIsNaOH commented on src/cleanup-desktop-shortcuts.hook/hook/post-install-all.ps1
> +    Write-Host "Removing '$($postshortcut.name)'"
Unfortunately, `-eq` does not work for comparing the two obects in this case, I tried it and the two are not the same according to `eq`. 

However, comparision of the fullname works, so I've updated it to use that, thanks for catching that @corbob

2022-11-01 21:13 UTC, TheCakeIsNaOH commented on src/cleanup-desktop-shortcuts.hook/hook/pre-install-all.ps1
> +[array]$global:cleanup_desktop_shortcuts_hook_pre_shortcuts = Get-Childitem -Path ([environment]::GetFolderPath("DesktopDirectory")) -Filter "*.lnk"
Updated.

2022-11-01 21:13 UTC, TheCakeIsNaOH commented on src/cleanup-desktop-shortcuts.hook/hook/post-install-all.ps1
> +[array]$global:cleanup_desktop_shortcuts_hook_post_shortcuts = Get-Childitem -Path ([environment]::GetFolderPath("DesktopDirectory")) -Filter "*.lnk"
I like both the hashtable and temporary module ideas. I've updated this to use the suggested hashtable, and can we continue this conversation over at #4?

2022-11-02 07:45 UTC, gep13 approved these changes
LGTM!

2022-11-02 07:47 UTC, gep13 commented
@TheCakeIsNaOH I have just taken this for a spin, and this looks really good to me, thank you very much for putting this together!

I will leave this open for a final review from @corbob and/or @vexx32 and once they are happy we can get this merged.

I have a final conversation that I need to have with @pauby regarding the versioning of the first package version, but that should happen this morning, and once a decision has been made, I can get the version number updated, if required.

Thanks again for pulling this together! Looking forward to showing this off tomorrow on the stream!

2022-11-02 10:44 UTC, gep13 commented on src/cleanup-desktop-shortcuts.hook/cleanup-desktop-shortcuts.hook.nuspec
> +    <version>0.0.1-pre</version>
Perhaps this should be `0.1.0-alpha-202201102`

2022-11-02 13:57 UTC, corbob approved these changes
LGTM! :shipit:

2022-11-03 13:48 UTC, gep13 approved these changes
LGTM!

2022-11-03 13:48 UTC, merged

2022-11-03 13:48 UTC, gep13 commented
@TheCakeIsNaOH thanks for getting this package created!